package com.wildan.uts_wildan

object NewsData {
    private val newsNames = arrayOf("TNI AD Bakal Proses Hukum Prajuritnya jika Terlibat Kasus Penembakan Pendeta Yeremia",
        "Raperpres Tugas TNI Atasi Terorisme Diminta Hargai Supremasi Sipil dan HAM",
        "Sofyan Djalil Sebut Mafia Tanah Juga Gunakan Buzzer di Media Sosial",
        "Saat \"Petinggi Kita\" dan \"Dikondisikan Atasan\" Muncul di Sidang 3 Oknum Penegak Hukum yang Terseret Kasus Djoko Tjandra",
        "Biden Siapkan Pemerintahan Transisi, Trump Lanjutkan Gugatan Hukum",
        "KPK Tak Hentikan Proses Hukum Selama Pilkada, Bagaimana Jika Kepala Daerah Terpilih Berstatus Tersangka?",
        "Kuasa Hukum Winda: Kalau Ingin Bertanya, Seharusnya Undang dan Tanyakan Langsung",
        "Pelaku Bullying Betrand Peto Minta Maaf, Tetap Proses Hukum",
        "Kuasa Hukum: Andi Irfan Jaya Tak Tahu Soal \"Action Plan\", apalagi Catut Nama Jaksa Agung",
        "Trump Kalah Pemilu AS, Tim Kampanyenya Siapkan Gugatan di Berbagai Negara Bagian")

    private val newsDetails = arrayOf("Komandan Pusat Polisi Milter Angkatan Darat (Danpuspomad), Letjen TNI Dodik Widjanarko memastikan akan menjerat hukum terhadap prajurit TNI AD apabila terbukti terlibat dalam kasus penembakan Pendeta Yeremia Zanambani di Intan Jaya, Papua. \"Masih dalam proses penyelidikan dan penyidikan oleh Tim Gabungan ( TNI AD), apabila di kemudian hari sudah didapat alat bukti yang cukup akan dilaksanakan proses hukum,\" ujar Dodik dalam konferensi pers, Kamis (12/11/2020). Dodik mengatakan, Tim Investigasi Gabungan TNI AD juga saat ini tengah menyelidiki kasus hilangnya dua orang yang ditahan di Koramil Sugapa pada 21 April 2020.",
        "Dekan Fakultas Hukum Universitas Indonesia (UI), Edmon Makarim menilai, Rancangan Peraturan Presiden tentang Tugas TNI dalam Mengatasi Aksi Terorisme harus mengedepankan supremasi sipil. Hal itu dilakukan guna memastikasn implementasi aturan tersebut dapat sejalan dengan upaya menghargai hak asasi manusia (HAM). \"UU tentang TNI dan UU mengenai penghargaan terhadap HAM dinyatakan ada penghargaan supremasi sipil, maka dengan sendirinya protap yang harus dijalankan TNI tentu harus menghargai itu (supremasi sipil dan HAM),\" ujar Edmon dalam webinar \"Peran TNI Mengatasi Aksi Terorisme dalam Menjaga Kedaulatan NKRI' yang digelar Sekolah Tinggi Hukum Militer\", Rabu (11/10/2020).",
        "Kementerian Agraria dan Tata Ruang/Badan Pertanahan Negara (ATR/ BPN) mencatat, sengketa konflik dan perkara pengadilan mengenai pertanahan berjumlah 9.000 kasus hingga Oktober 2020. Jumlah kasus konflik pertanahan ini tersebar di seluruh wilayah Indonesia. Menteri ATR/Kepala BPN Sofyan A Djalil mengatakan, salah satu penyebab maraknya sengketa pertanahan tersebut berasal dari mafia tanah. \"Kami keras sekali dengan mafia tanah. Tapi untuk diketahui, mafia itu juga fight back (melawan),\" tegas Sofyan dalam konferensi pers virtual, Selasa (11/11/2020). Bahkan, mafia tanah tersebut menggunakan jasa  buzzer di platform media sosial untuk melawan Pemerintah.",
        "Tiga aparat penegak hukum yang terseret kasus pelarian buronan kelas kakap, Joko Soegiarto Tjandra alias Djoko Tjandra, sudah memasuki tahap persidangan. Adapun ketiganya terdiri dari Irjen Napoleon Bonaparte, Brigjen (Pol) Prasetijo Utomo, dan Jaksa Pinangki Sirna Malasari. Napoleon dan Prasetijo tersandung kasus dugaan korupsi terkait penghapusan red notice di Interpol atas nama Djoko Tjandra. Kasus ini ditangani oleh Bareskrim Polri. Sementara, Pinangki merupakan terdakwa kasus dugaan korupsi terkait kepengurusan fatwa di Mahkamah Agung (MA). Kejaksaan Agung yang menangani kasus ini. Salah satu hal yang muncul saat sidang dan menjadi sorotan adalah munculnya sebutan “petinggi kita” serta soal atasan dari para aparat penegak hukum tersebut.",
        "Presiden Donald Trump melanjutkan gugatan hukumnya terhadap kasus-kasus pelanggaran dalam pemilu presiden Amerika. Sementara itu, mantan Wakil Presiden Joe Biden yang diproyeksikan VOA menjadi pemenang pemilihan presiden ini mengatakan akan membentuk gugus tugas penanganan pandemi virus corona atau Covid-19 minggu ini.  Mantan Wakil Presiden Joe Biden, yang diproyeksikan memenangi pemilihan presiden ini, mengatakan akan memulai transisi untuk memerintah. Adapun Presiden Donald Trump mengatakan, surat-surat suara masih dihitung di beberapa negara bagian dan ia seharusnya diberi kesempatan untuk mengajukan gugatan hukum di beberapa negara bagian di mana terdapat tuduhan kecurangan. Gubernur negara bagian South Dakota, Kristi Noem yang berasal dari Partai Republik, mengatakan, “Yang menarik adalah pernyataan sejumlah individu yang mengatakan ini merupakan kemenangan yang sangat luar biasa bagi Joe Biden. Padahal, tidak demikian, karena ada beberapa negara bagian yang masih melakukan penghitungan suara.” Sejumlah pemimpin Partai Demokrat menyerukan kepada mitra-mitra mereka di Partai Republik untuk menerima hasil pemilihan presiden demi negara ini atau membuktikan adanya kecurangan yang dituduhkan.",
        "Ketua Komisi Pemberantasan Korupsi ( KPK) Firli Bahuri menegaskan, KPK akan tetap melakukan proses hukum di tengah penyelanggaraan pemilihan kepala daerah. \"Saya ingin sampaikan dalam kesempatan ini, proses hukum selama Pilkada, KPK tidak pernah berhenti proses hukum walaupun Pilkada sekalipun,\" kata Firli dalam acara Webinar Pembekalan Cakada yang disiarkan akun Youtube Kanal KPK, Selasa (10/11/2020). Firli mengatakan, proses politik melalui Pilkada tidak akan menghalangi proses hukum yang dilakukan KPK. Begitupun sebaliknya, proses hukum tidak boleh menghalangi proses politik. Firli menuturkan, apabila seorang kepala daerah terpilih berstatus sebagai tersangka, maka kepala daerah tersebut akan tetap dilantik.",
        "Kuasa Hukum Winda Earl, Joey Pattinasarany mengaku percaya pihak penyidik Mabes Polri akan mengusut tuntas kasus raibnya uang Rp 22 miliar milik Winda dan ibunya di Maybank Indonesia. Joey menyatakan, memang patut diduga bahwa uang kliennya bisa hilang bukan karena perbuatan oknum Maybank Indonesia semata. \"Kami selalu percaya bahwa pihak Bareskrim Mabes Polri akan mengusut tuntas kasus ini sedalam-dalamnya, karena patut diduga bahwa uang nasabah kami hilang bukan kesalahan oknum Maybank semata,\" kata Joey kepada Kompas.com, Selasa (10/11/2020).",
        "Pelaku bullying Betrand Peto datang dari Lampung untuk meminta maaf secara langsung kepada presenter Ruben Onsu, ayah Betrand Peto. Meskipun sudah menerima permintaan maaf pelaku, Ruben Onsu tetap akan membawa kasus itu ke jalur hukum. Berikut rangkuman Kompas.com. Baca juga: Reaksi Ruben Onsu soal Bullying terhadap Betrand Peto Minta maaf secara langsung Bertemu dengan Ruben Onsu beserta kuasa hukumnya, pelaku bullying Betrand yang masih di bawah umur meminta maaf atas kelakuannya. \"Datang ingin bertemu dengan Ruben untuk meminta maaf didampingi oleh keluarganya,\" kata Minola Sebayang, kuasa hukum Ruben Onsu. Respons baik Ruben Onsu Ruben merespons dengan baik kedatangan pelaku dan keluarga untuk menyelesaikan masalah tersebut. Baca juga: Ruben Onsu Akan Laporkan 20 Akun yang Hina Betrand Peto \"Iya kalau saya merespons baikah, sampai akhirnya saya mau menerima untuk bertemu tapi semua sudah saya serahkan ke kuasa hukum,\" ujar Ruben Onsu.",
        "Pengusaha Andi Irfan Jaya mengaku tidak mengetahui adanya proposal action plan dalam rangka mendapatkan fatwa di Mahkamah Agung (MA) untuk Djoko Tjandra. Andi juga mengaku tidak mengetahui soal nama Jaksa Agung Sanitiar (ST) Burhanuddin dan mantan Ketua MA, Hatta Ali yang tercantum dalam action plan itu. “Jika terdapat nama-nama yang disebutkan dalam action plan seperti HA dan BR, maka terdakwa sama sekali tidak mengetahui adanya pencantuman nama-nama tersebut,” demikian bunyi dokumen eksepsi Andi yang diterima Kompas.com, Senin (9/11/2020).",
        "Kandidat presiden dari Partai Demokrat, Joe Biden, telah dinyatakan sebagai presiden terpilih. Namun, kandidat petahana, Presiden Donald Trump, masih berencana melayangkan gugatan terhadap hasil perhitungan suara di sejumlah negara bagian kunci pertarungan Pilpres AS. Pengacara Trump, Rudy Giuliani, mengatakan kepada Fox News bahwa bakal keliru jika Trump menyatakan kekalahan karena ada bukti kuat bahwa di setidaknya tiga atau empat negara bagian, dan mungkin 10, hasil pemilu telah dicuri. Tim kampanye Trump belum menyediakan bukti kuat yang dimaksud, namun mereka berencana melayangkan gugatan di sejumlah negara bagian pada Senin (9/11/2020).")

    private val newsImages = arrayOf("https://asset.kompas.com/crops/_ogIvqZop6cjbN_-iArI9-sfxPs=/125x0:800x450/750x500/data/photo/2020/11/11/5fab1486b5108.jpg",
        "https://asset.kompas.com/crops/nch-gjXXPi7n9Jddu50kxSKZjko=/0x0:0x0/750x500/data/photo/2020/11/05/5fa359ddaf019.jpg",
        "https://asset.kompas.com/crops/BiE3WhmW0n2iR1uN_yWJ0qZTTeU=/0x208:1181x996/750x500/data/photo/2020/01/22/5e27ab90e44d2.jpeg",
        "https://asset.kompas.com/crops/8hzKfLeFFii7XgKHlVsR9DfkjX8=/0x0:999x666/750x500/data/photo/2020/11/10/5faa982865981.jpg",
        "https://asset.kompas.com/crops/nSHpSkwuzii6TwJdFA0JHup9zUo=/72x3:637x380/750x500/data/photo/2020/11/07/5fa69eb6f1d11.jpg",
        "https://asset.kompas.com/crops/Q07Me1lt-5OH5jH53gQXZfVHhLE=/0x0:900x600/750x500/data/photo/2019/01/22/4091862233.jpg",
        "https://asset.kompas.com/crops/paLVTwBTRQxDCWWoEn4ifwX50AU=/0x0:1000x667/750x500/data/photo/2020/08/30/5f4b8df10888a.jpg",
        "https://asset.kompas.com/crops/PtwsaI9GxEdmqkoA_G8jxnhad2Q=/0x0:0x0/750x500/data/photo/2020/03/11/5e6910d0a28c5.jpg",
        "https://asset.kompas.com/crops/Co6xlF6sY3wM65-B50ZRTfqx-58=/0x0:999x666/750x500/data/photo/2020/09/02/5f4faa00646e2.jpg",
        "https://asset.kompas.com/crops/qXwKHvnnSVmSvCeiLnrNSxlHzbM=/0x0:800x533/750x500/data/photo/2020/11/07/5fa61c9dd0b34.jpg")

    val listData: ArrayList<News>
        get() {
            val list = arrayListOf<News>()
            for (position in newsNames.indices){
                val news = News()
                news.name = newsNames[position]
                news.detail = newsDetails[position]
                news.photo = newsImages[position]
                list.add(news)
            }
            return list
        }
}